config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/works',   to: 'static_pages#works'
  get  '/cv',      to: 'static_pages#cv'
  get  '/contact',      to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def works
  end

  def cv
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Makoto Ishii"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p>
      &copy;2019 Makoto Ishii
    </p>
</footer>

app/views/layouts/_header.html.erb
<header class="">
  <div class="container">
    <%= link_to "Makoto Ishii", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "News",    root_path %></li>
        <li><%= link_to "Works",   works_path %></li>
        <li><%= link_to "Cv",      cv_path %></li>
        <li><%= link_to "Contact",      contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<div class="">
  <p>My home pages of contact</p>
</div>

app/views/static_pages/cv.html.erb
<% provide(:title, "Cv") %>
<h1>Cv</h1>
<div class="cv_image">
  <img src="/assets/sample.jpg" alt="画像" width="200">
</div>
<div class="cv_text">
  <p>
    石居　真信 <br>
    <br>
    1992　　　　埼玉生まれ<br>
    2017　　　　東京造形大学　卒業<br>
  </p>
  <p>
    個展<br>
    2019       『ジョンには見えている』　/  Breaveness Contemporary
  </p>
  <p>
    グループ展 <br>
    2017       『ZOKEI展（卒業制作展）』 / 東京造形大学 <br>
    2018    　　『作品を「飾る」#1 』 / 相原スタジオ　<br>
  </p>
  <p>
    パフォーマンス <br>
    2018        Super Open Studio 2018『できるだけ誠実にやる気のある灰を残す』 / アートラボ橋本
  </p>
  <p>
    参加 <br>
     2018　『スペクタクルの林間学校』（シアターコモンズ・ラボ / 冬季集中ラボ ） / SHIBAURA HOUSE
  </p>
</div>
<div class="after">

</div>

app/views/static_pages/home.html.erb
<div class="center">
   <img src="/assets/1080P_04.00_00_00_00.Still001.jpg" alt="main image" width="1140">
</div>
<h1>News</h1>
<div class="">
  <p>
    My home peges of news
  </p>
</div>

app/views/static_pages/works.html.erb
<% provide(:title, "Works") %>
<h1>Works</h1>
<div class="">
  <p>My home pages of works</p>
</div>